### ISSUE TITLE
timeseries guide - wrong use of ts.alter

### ISSUE THREAD

**Issue by K-Jo** [RedisInsight/Guides#23]
You can also update an existing time series using the TS.ALTER command.

TS.ALTER // Updates existing data points
    sensor1 // Keyname for the timerseries
    1626434639000 // Timestamp
    26 // Value

https://redis.io/commands/ts.alter/

ts.alter is to update metadata, not samples.
updating samples is via ts.add

**Comment by ViktarStarastsenka** [comment]
raised a PR:
https://github.com/RedisInsight/Guides/pull/24
