### ISSUE TITLE
duplicated pages with same content

### ISSUE THREAD

**Issue by TianMing2018** [RedisInsight/Guides#27]
those files have same content:
- </quick-guides/vector-similarity-search/loading-vectors.md> and </quick-guides/vector-similarity-search/load-vectors.md>
- </quick-guides/vector-similarity-search/querying-vectors.md> and </quick-guides/vector-similarity-search/query-vectors.md>

**Comment by ViktarStarastsenka** [comment]
thank you! Guides will be updated with the 2.16 release (will be available in late December).
